name: barcoder
description: A fun hobby project for cataloging book collections. 

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_barcode_scanner: ^1.0.1
  http: ^0.12.2
  googleapis: ^0.56.1
  provider: ^4.3.2+3
  shared_preferences: '>=0.5.12+4 <2.0.0'
  
dev_dependencies:
  pedantic: ^1.9.2

flutter:
  uses-material-design: true